services:
  app:
    image: ${HARBOR_REGISTRY:-192.168.0.51:8080}/rvscope/rvscope:${RVSCOPE_IMAGE_TAG:-homolog}
    pull_policy: always
    container_name: rvscope_app
    restart: unless-stopped
    environment:
      CI_ENVIRONMENT: ${CI_ENVIRONMENT:-production}
      APP_STAGE: ${APP_STAGE:-homologation}
      APP_IMAGE_TAG: ${RVSCOPE_IMAGE_TAG:-homolog}
    ports:
      - "8443:8443"
    volumes:
      - ./.env:/var/www/html/.env:Z
      - ./writable:/var/www/html/writable:Z
      - ./imports:/app/imports:Z
      - ./certs:/etc/ssl/private:ro,Z
